#!/usr/bin/env python

import argparse
import subprocess
from gitutils import filter_changes


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--ignore-untracked',
                        dest='ignore_untracked',
                        action='store_true',
                        default=False,
                        help='ignore untracked files.')
    parser.add_argument('regex',
                        metavar='regex',
                        type=str,
                        nargs=1,
                        help='filter regular expression')
    args = parser.parse_args()

    subprocess.call(['git', 'checkout'] + filter_changes(args.regex[0], args.ignore_untracked))


if __name__ == '__main__':
    main()
